<?php

namespace ContainerLco6ICf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_OB7O6bkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.oB7O6bk' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Application/CommandHandler/CalculateProductAuctionResultCommandHandler.php';

        return $container->privates['.messenger.handler_descriptor.oB7O6bk'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Application\CommandHandler\CalculateProductAuctionResultCommandHandler(($container->privates['App\\Infrastructure\\Persistence\\Doctrine\\Repository\\Product\\MysqlProductRepository'] ?? $container->load('getMysqlProductRepositoryService'))), ['bus' => 'commands.bus']);
    }
}
