<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLco6ICf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLco6ICf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLco6ICf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLco6ICf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLco6ICf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lco6ICf',
    'container.build_id' => '0c29e4fe',
    'container.build_time' => 1696944617,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLco6ICf');
